capstone_01
2004-okari/CAPSTONE-01 pull request #1
Opened 2023-06-28 18:27 UTC by 2004-okari

In the capstone project.

1. The home page has a link in the menu to the About page.
2. The logo in the header links to the home page.
3. When the user clicks the hamburger button on the header, the mobile menu appears over the page.
4. The mobile menu has a close (X) button that closes the menu.
5. The section "Featured speakers" has been created dynamically in JavaScript.
6. Given the author credit in the READme.md under the acknowledgements page.
7. Link to private video:

2023-06-28 19:53 UTC, Ibizugbe requested changes
Hi @2004-okari 👋👋👋,

![tryagain](https://github.com/2004-okari/CAPSTONE-01/assets/64643995/7e1a6c75-d884-47ab-a11c-3b2f4d7287a2)
 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Highlights✅✅

- [x] Linters are passing👍.
- [x] Project is deployed with github pages👍.
- [x] Gitflow is used👍.
- [x] Speaker section is generated dynamically from the array of object containing details about speakers👍.
- [x] `home` and `about` page have been created and it is easy to navigate between both👍.
- [x] all images have `alt` values👍.


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [OPTIONAL] Try to ensure your commit messages are capitalised, descriptive and meaningful as this is a display of professionalism😉.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-28 19:53 UTC, Ibizugbe commented on index.js
> +}
Nice Job so far👍. Currently, your navbar functionalities doesn't work as required. When the hamburger is clicked, a mobile menu should be displayed with the different navigation links😉. currently, when it is clicked, nothing happens. kindly do well to fix this👍.
<img width="780" alt="image" src="https://github.com/2004-okari/CAPSTONE-01/assets/64643995/71ad013d-dc6a-4fe5-8251-7400673d6abd">

https://github.com/2004-okari/CAPSTONE-01/assets/64643995/31c55fa1-e691-4627-8977-7193409d8b0c

2023-06-28 19:53 UTC, Ibizugbe commented on index.html
> +    </div>
Kindly ensure the links on the top dark bar are properly aligned to match the given design as this is a requirement for this milestone that we try to stick to the design even as we personalize the content of the page😉.

yours
<img width="946" alt="image" src="https://github.com/2004-okari/CAPSTONE-01/assets/64643995/38564593-2f90-4cea-be2d-038785a4189f">

design
<img width="650" alt="image" src="https://github.com/2004-okari/CAPSTONE-01/assets/64643995/514340c4-ebda-48a5-ae14-f776b8f6ab76">


on mobile, to match the design, you don't need the company logo.

yours
<img width="295" alt="image" src="https://github.com/2004-okari/CAPSTONE-01/assets/64643995/ed50ebcf-7c93-4834-b1af-782e4c011421">

design
<img width="341" alt="image" src="https://github.com/2004-okari/CAPSTONE-01/assets/64643995/244ff087-5f1a-4a7c-b0e9-5ba2f6470f78">

Also ensure the hamburger is transparent as shown in the design😉.

2023-06-28 19:53 UTC, Ibizugbe commented on index.html
> +      </section>
I see this is meant to be the footer section, Hence it is more semantic you wrap it in a `footer` instead of a `section` tag and it should be after the `main` section😉.

also from the design, don' the footer on the About page should have a dark background so as to match the design👍.

In summary, your footer should be consistent on both pages, but the only difference should be the color😉. So when the semantic tag change is implemented, it should also be consistent on the About page👍.

your about footer
<img width="942" alt="image" src="https://github.com/2004-okari/CAPSTONE-01/assets/64643995/0838f7e2-37e4-4212-8cdf-63a7b3e73bea">

design
<img width="577" alt="image" src="https://github.com/2004-okari/CAPSTONE-01/assets/64643995/7eaac5d4-1666-4c2b-8c51-6d5cf835ce58">

Kindly make the necessary changes😉.

2023-06-28 19:53 UTC, Ibizugbe commented on index.js
> +});
Nice job rendering the `speakers` section dynamically😉. But let's try to match the given design😉. From the design, the speaker section consist of two columns each and not three as you have used😉.

yours 
<img width="943" alt="image" src="https://github.com/2004-okari/CAPSTONE-01/assets/64643995/c5e0b519-65d9-41c6-ac81-dc16ef3ca241">

design
<img width="622" alt="image" src="https://github.com/2004-okari/CAPSTONE-01/assets/64643995/e6799c34-24f0-4ce1-93c6-d5d117cb1b0a">

also, don't forget to consider the spacings😉.

2023-06-28 19:53 UTC, Ibizugbe commented on index.html
> +    </main>
On mobile, the page ends with a `see more` button and not a footer😉. also, there are just a couple of speakers and not all the speakers😉. let's make this change to make your project match the deisgn.😉

design
<img width="328" alt="image" src="https://github.com/2004-okari/CAPSTONE-01/assets/64643995/18679175-efa8-4eca-adf1-0c3503b2142d">

yours
<img width="331" alt="image" src="https://github.com/2004-okari/CAPSTONE-01/assets/64643995/8437a89f-02e8-4b85-9ef8-a05503f213e6">

also take note of the spacings around the speaker cards and implement the changes as necessary👍.

2023-06-28 19:53 UTC, Ibizugbe commented on index.css
> +      display: none;
Please Kindly make use of the right colors for your styling as this is a requirement for this milestone. this makes our project match the given design👍.
<img width="316" alt="image" src="https://github.com/2004-okari/CAPSTONE-01/assets/64643995/13e28945-7368-4f27-8e96-3330bb063827">

2023-06-28 19:53 UTC, Ibizugbe commented on index.html
> +          <p class="minor-date-text">@ Microsoft offices of Kenya, Tech Centre and more</p>
Kindly obey the header hierarchy rule for accessibility's sake😉. You have done a nice job using an `h1` tag for the main header👍. the next hierarchy should be a `h2`  and then, each section should start with a `h2` tag and the subsequent header will use the next hierarchy. `h3`, `h4` etc. shows the hierarchy of the headers (which is under which😉).
ensure this is implemented in your home and about page👍.

2023-06-30 08:39 UTC, V-Blaze requested changes
## Hi @2004-okari , 

# Almost there 🟡 

![giphy](https://user-images.githubusercontent.com/107632780/228988839-8679641a-a056-4909-a594-bcecacef173b.gif)


Great work so far, You have come a long way, keep moving forward👏 👍  
You've done well implementing the project requirements, and some changes from the previous reviewers, but there are still some issues I think you need to improve on. 😄 👋 


 ## Highlights
- Mobile menu works great✔
- Clean and organized code :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-30 08:39 UTC, V-Blaze commented on index.js
> +  {
- [ ] You have done great implementing most of the requested changes from the previous reviewer. :+1: But there are still some changes you need to make.
- - As suggested by the previous reviewer, your Featured speaker section has 3 rows but the given design has just 2. I'll suggest you update your CSS to implement this as you are meant to replicate the given design. :smile: :wave: 

- - Your design:
 
![Selection_074](https://github.com/2004-okari/CAPSTONE-01/assets/107632780/90fe1cf3-108b-473d-8b44-1b7a077f6d64)

- - Given design:
![Screenshot from 2023-06-30 09-26-37](https://github.com/2004-okari/CAPSTONE-01/assets/107632780/5a74dd67-4a5a-4770-b9b5-9694881648e4)

2023-06-30 08:39 UTC, V-Blaze commented on index.html
> +        </div>
- [ ] As pointed out by the previous reviewer, you can see that not all the speakers are shown on mobile. It shows only two with a `more button`, I'll suggest you implement this on your project. :clap: 

- - Your design:
![Screenshot from 2023-06-30 09-21-24](https://github.com/2004-okari/CAPSTONE-01/assets/107632780/944f4bf6-854b-4eab-9fd1-668bd20cee60)

- - Given design:
![Screenshot from 2023-06-30 09-21-55](https://github.com/2004-okari/CAPSTONE-01/assets/107632780/699e606d-2e80-45b9-9163-c9391a714968)

- [ ] Also as the previous reviewer pointed out, the `Partner and the footer` section are not visible on mobile screens according to the design. I'll suggest you update your CSS to hide these sections on mobile and display them when on desktop screens. :smile: :+1:

2023-07-01 18:12 UTC, franclobo approved these changes
Hi @2004-okari, 

# STATUS: APPROVED 😃 

![leonardo-dicaprio-leo-dicaprio](https://github.com/2004-okari/CAPSTONE-01/assets/58642949/ac41738c-270d-4523-8948-3e870b28de50)

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

## Highlights

- No linter errors ✔️ 
- Descriptive Pr ✔️ 
- Correct Git flow ✔️ 
- Best practices of HTML, CSS, and JavaScript ✔️ 
- Good UI and UX ⭐ ⭐ ⭐ ⭐ ⭐ 

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-09-18 21:11 UTC, merged